---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tomcat-{{ .Values.namespacePermissions.user }}
  labels:
    {{- include "tomcat.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.namespacePermissions.role }}
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: {{ .Values.namespacePermissions.user }}
