apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: software-templates
  description: A collection of Backstage templates for devhub-mad
spec:
  type: url
  targets:
    - scaffolder-templates/frontend/template.yaml
    - scaffolder-templates/spring-backend/template.yaml
    - scaffolder-templates/quarkus-backend/template.yaml
    - scaffolder-templates/gateway/template.yaml
    - scaffolder-templates/wheres-teddy/template.yaml
    - scaffolder-templates/vote-ui-python/template.yaml