apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: software-templates
  description: A collection of Backstage templates for devhub-mad
spec:
  type: url
  targets:
    - scaffolder-templates/frontend/template.yaml
    - scaffolder-templates/spring-backend/template.yaml
    - scaffolder-templates/gateway/template.yaml
    - scaffolder-templates/vote-ui-python/template.yaml
    - scaffolder-templates/tomcat-vm/template.yaml
    - scaffolder-templates/windows-vm/template.yaml
    - scaffolder-templates/rhel9-vm-medium/template.yaml
    - scaffolder-templates/rhel9-vm-large/template.yaml