applicationName: ${{values.component_id}}
namespace: ${{values.namespace}}
targetEnvironment: dev
version: "1.0.0"
portName: 8080-tcp
port: 8090
targetPort: 8090
portHTTPS: 8443
targetPortHTTPS: 8443
portNameHTTPS: 8443-tcp
portName8778: 8778-tcp
port8778: 8778
targetPort8778: 8778
app:
  namespace: ${{values.namespace}}


routes: []
deploymentStrategy:
  type: RollingUpdate
  rollingMaxSurge: 25%
  rollingMaxUnavailable: 20%
replicaCount: 1
health:
  livenessEndpoint: /actuator/health
  readinessEndpoint: /actuator/health
  probeDelay: 5
  probePeriod: 10
  probeTimeout: 2
env: 
    - name: COMPONENT_CATALOG_HOST
      value: catalog-apps
    - name: COMPONENT_CATALOG_PORT
      value: '8080'
    - name: COMPONENT_INVENTORY_HOST
      value: inventory-app
    - name: COMPONENT_INVENTORY_PORT
      value: '8080'
autoscaling:
  enabled: false
namespace:
  enabled: true
  name: ${{values.namespace}}
  argocd:
    name: ${{values.component_id}}

replicaCount: 1

image:
  repository: ${{values.image_host}}/${{values.image_name}}
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ${{values.image_tag}}

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

namespace:
  enabled: true
  name: ${{values.namespace}}
  argocd:
    name: default