---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: {{ include "tomcat.fullname" . }}
  labels:
    {{- include "tomcat.labels" . | nindent 4 }}
    {{- include "backstage.labels" . | nindent 4 }}
spec:
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: medium
        vm.kubevirt.io/os: rhel8
        vm.kubevirt.io/workload: server
      labels:
        kubevirt.io/domain: {{ include "tomcat.fullname" . }}
        kubevirt.io/size: medium
        {{- include "tomcat.labels" . | nindent 8 }}
        {{- include "backstage.labels" . | nindent 8 }}   
    spec:
      domain:
        devices:
          disks:
            - name: vol-0
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
          {{- if .Values.staticIP }}
          - bridge: {}
            name: nic-secondary
          {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      networks:
      - name: default
        pod: {}
      livenessProbe:
        httpGet:
          path: /health/live
          port: 8080
        initialDelaySeconds: 60
        periodSeconds: 30
        timeoutSeconds: 10
      readinessProbe:
        httpGet:
          path: /health/ready
          port: 8080
        initialDelaySeconds: 60
        periodSeconds: 30
        timeoutSeconds: 10
      nodeSelector:
        node-role.kubernetes.io/metal: ''
      tolerations:
        - key: metal
          operator: Exists
      volumes:
      - name: vol-0
        dataVolume:
          name: tomcat
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            user: cloud-user
            password: openshift
            chpasswd: { expire: False }
            ssh_pwauth: true
            {{- if .Values.staticIP }}
            bootcmd:
            - nmcli connection modify "Wired connection 2" ipv4.addresses {{ .Values.staticIP }} ipv4.method manual
            - nmcli dev reapply eth1
            {{- end }}
        name: cloudinitdisk
  dataVolumeTemplates:
    - metadata:
        creationTimestamp: null
        name: tomcat
      spec:
        storage:
          resources:
            requests:
              storage: 40Gi
        source:
          http:
            url: {{ .Values.image.url }}