---
apiVersion: v1
kind: Secret
metadata:
  name: ${{values.component_id}}-repo
  namespace: globex-devhub
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: ${{values.destination}}
